dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.109.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.109.0
    # NOTE: Prior to v0.86.0 use the `loggingexporter` instead of `debugexporter`.
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.109.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.109.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.109.0
