name: Package Tests

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      distribution:
        required: true
        type: string
      issue-on-failure:
        required: false
        type: boolean
        default: false
        description: "Set to true if a GH issue should be generated upon failure"

permissions:
  contents: read

jobs:
  package-tests:
    name: Package Tests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        type: ${{ fromJSON(inputs.type) }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Download built artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: linux-packages

      - name: Test ${{ matrix.type }} package
        run: ./scripts/package-tests/package-tests.sh ./otelcol*-next_linux_amd64.${{ matrix.type }} ${{ inputs.distribution }}

  create-issue:
    name: Create GitHub Issue
    runs-on: ubuntu-24.04
    needs: [package-tests]
    if: failure() && inputs.issue-on-failure == 'true'
    steps:
      - name: Formulate issue
        id: formulate_issue
        run: |
          # create a markdown file that contains details about the failure
          echo "The nightly linux package tests failed in the following GitHub actions run." > nightly-test-failure.md
          echo "* Link to run: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> nightly-test-failure.md
          echo "* Triggered by: Nightly scheduled build" >> nightly-test-failure.md
          echo "" >> nightly-test-failure.md
          echo "Note: This issue was auto-generated from [base-package-tests.yaml](https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/.github/workflows/base-package-tests.yaml)" >> nightly-test-failure.md

      - name: Create issue on failure
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh issue create \
            --repo open-telemetry/opentelemetry-collector-contrib \
            --title "Nightly Linux Package Tests Failed" \
            --body-file nightly-test-failure.md \
            --label "release:blocker"
