name: MSI Tests

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      distribution:
        required: true
        type: string

jobs:
  msi-tests:
    name: MSI Tests
    runs-on: otel-windows-latest-8-cores
    strategy:
      matrix:
        type: ${{ fromJSON(inputs.type) }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download built artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: msi-packages

      - name: Set MSI tests required environment variables
        run: |
          $ErrorActionPreference = 'Stop'
          Set-PSDebug -Trace 2
          Get-ChildItem -Path .\*.msi -Recurse
          Resolve-Path .\*.msi
          $msi_path = Resolve-Path .\*.msi
          $msi_path
          Test-Path $msi_path
          $alt_config_path = Resolve-Path .\distributions\${{ inputs.distribution }}\config.yaml
          Test-Path $alt_config_path
          "MSI_TEST_ALTERNATE_CONFIG_FILE=$alt_config_path" | Out-File -FilePath $env:GITHUB_ENV -Append
          "MSI_TEST_COLLECTOR_PATH=$msi_path" | Out-File -FilePath $env:GITHUB_ENV -Append
          "MSI_TEST_COLLECTOR_SERVICE_NAME=${{ inputs.distribution }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Run the MSI tests
        working-directory: tests/msi
        run: |
          go test -timeout 15m -v ./...
