name: Package Tests

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      distribution:
        required: true
        type: string

jobs:
  package-tests:
    name: Package Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ${{ fromJSON(inputs.type) }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download built artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: linux-packages

      - name: Test ${{ matrix.type }} package
        run: ./scripts/package-tests/package-tests.sh ./otelcol*-SNAPSHOT-*_linux_amd64.${{ matrix.type }} ${{ inputs.distribution }}
