name: Update Version in Distributions and Prepare PR
on:
  workflow_dispatch:
    inputs:
      next_beta_core:
        description: 'Collector core beta module set version to update to. Leave empty to bump to next minor version (e.g. 0.120.1 -> 0.121.0)'
        required: false
        default: ''
      next_beta_contrib:
        description: 'Collector contrib beta module set version to update to. Leave empty to bump to next minor version (e.g. 0.120.1 -> 0.121.0)'
        required: false
        default: ''
      next_stable_core:
        description: 'Collector core stable module set version to update to. Leave empty to bump to next minor version (e.g. 1.26.0 -> 1.27.0)'
        required: false
        default: ''

jobs:
  update-version:
    runs-on: ubuntu-24.04
    
    permissions:
      contents: write # required for pushing changes
      pull-requests: write # required for creating PR

    steps:
      - uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_COLLECTOR_RELEASES_APP_ID }}
          private-key: ${{ secrets.OTELBOT_COLLECTOR_RELEASES_PRIVATE_KEY }}

      - name: Set up commit author name and email
        id: committer
        run: |
          git config --global user.name "otelbot"
          git config --global user.email "197425009+otelbot@users.noreply.github.com"

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ steps.otelbot-token.outputs.token }}

      - name: Run bump-versions.sh
        run: |
          .github/workflows/scripts/bump-versions.sh --commit --pull-request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          next_beta_core: ${{ github.event.inputs.next_beta_core }}
          next_beta_contrib: ${{ github.event.inputs.next_beta_contrib }}
          next_stable_core: ${{ github.event.inputs.next_stable_core }}
