name: Update Version in Distributions and Prepare PR
on:
  workflow_dispatch:
    inputs:
      next_beta_core:
        description: 'Collector core beta module set version to update to (e.g. 0.120.1 -> 0.121.0)'
        required: true
        type: choice
        options:
          - minor
          - patch
        default: minor
      next_beta_contrib:
        description: 'Collector contrib beta module set version to update to (e.g. 0.120.1 -> 0.121.0)'
        required: true
        type: choice
        options:
          - minor
          - patch
        default: minor
      next_stable_core:
        description: 'Collector core stable module set version to update to (e.g. 1.26.0 -> 1.27.0)'
        required: true
        type: choice
        options:
          - minor
          - patch
        default: minor

jobs:
  update-version:
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run bump-versions.sh
        run: |
          .github/workflows/scripts/bump-versions.sh --commit --pull-request
        env:
          next_beta_core: ${{ github.event.inputs.next_beta_core }}
          next_beta_contrib: ${{ github.event.inputs.next_beta_contrib }}
          next_stable_core: ${{ github.event.inputs.next_stable_core }}
