name: Update Version

on:
  workflow_dispatch:
    inputs:
      old_version:
        description: 'Previous semantic version number (e.g., v0.109.0)'
        required: true
      new_version:
        description: 'Next semantic version number (e.g., v0.110.0)'
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Strip 'v' from new version for OTELCOL_BUILDER_VERSION
        uses: bhowell2/github-substring-action@latest
        id: strip_new_version
        with:
          value: ${{ github.event.inputs.new_version }}
          index_of_str: 'v'
      - name: Strip 'v' from old version for OTELCOL_BUILDER_VERSION
        uses: bhowell2/github-substring-action@latest
        id: strip_old_version
        with:
          value: ${{ github.event.inputs.old_version }}
          index_of_str: 'v'
      
      - name: Update version in Makefile
        run: |
          sed -i "s/OTELCOL_BUILDER_VERSION ?= ${{ steps.strip_old_version.outputs.substring }}/OTELCOL_BUILDER_VERSION ?= ${{ steps.strip_new_version.outputs.substring }}/g" Makefile

      - name: Update version in builder-config.yaml
        run: |
          sed -i "s/${{ github.event.inputs.old_version }}/${{ github.event.inputs.new_version }}/g" cmd/builder/builder-config.yaml

      - name: Update version in otelcol manifest.yaml
        run: |
          sed -i "s/${{ github.event.inputs.old_version }}/${{ github.event.inputs.new_version }}/g" distributions/otelcol/manifest.yaml

      - name: Update version in otelcol-contrib manifest.yaml
        run: |
          sed -i "s/${{ github.event.inputs.old_version }}/${{ github.event.inputs.new_version }}/g" distributions/otelcol-contrib/manifest.yaml

      - name: Update version in otelcol-k8s manifest.yaml
        run: |
          sed -i "s/${{ github.event.inputs.old_version }}/${{ github.event.inputs.new_version }}/g" distributions/otelcol-k8s/manifest.yaml

      - name: Commit changes and draft PR
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-version-${{ github.event.inputs.new_version }}
          git add Makefile cmd/builder/builder-config.yaml distributions/otelcol/manifest.yaml distributions/otelcol-contrib/manifest.yaml distributions/otelcol-k8s/manifest.yaml
          git commit -m "Update version from ${{ github.event.inputs.old_version }} to ${{ github.event.inputs.new_version }}"
          git push -u origin update-version-${{ github.event.inputs.new_version }}
          gh pr create --title "[chore] Prepare release ${{ github.event.inputs.new_version }}" \
            --body "This PR updates the version from ${{ github.event.inputs.old_version }} to ${{ github.event.inputs.new_version }}" \
            --base main --head update-version-${{ github.event.inputs.new_version }} --draft
